[package]
name = "kline_downloader_rust"
version = "0.1.0"
edition = "2021"
description = "A Rust application to download Binance U-margined perpetual futures kline data"
authors = ["Quant Team"]

[dependencies]
tokio = { version = "1.28", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
clap = { version = "4.3", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"
futures = "0.3"
tokio-stream = "0.1"
csv = "1.2"
tracing = "0.1"
tracing-subscriber = "0.3"
rusqlite = { version = "0.29", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.22"
