# 币安K线系统统一配置文件
# K线聚合系统配置 - 符合 AggregateConfig 结构体格式

# ============================================================
# 顶层通用配置
# ============================================================

# 支持的时间周期列表
supported_intervals = ["1m", "5m", "30m", "1h", "4h", "1d", "1w"]

# 系统设计的最大品种数量。这是一个硬性上限，
# Gateway 和 Worker 的内存分配都将基于此值。
# 它必须足够大以容纳所有当前和未来可能上市的品种。
# 临时调整为较小值以避免栈溢出
max_symbols = 1000

# 缓冲区切换间隔（毫秒）
buffer_swap_interval_ms = 1000

# 注意：persistence_interval_ms 已移除
# 数据持久化频率现在由 gateway.pull_interval_ms 间接控制

# Actor心跳间隔（秒）
actor_heartbeat_interval_s = 5

# Watchdog检查间隔（秒）
watchdog_check_interval_s = 15

# Watchdog Actor超时阈值（秒）
watchdog_actor_timeout_s = 60

# Actor通道容量（有界通道的缓冲区大小）
channel_capacity = 100

[database]
database_path = "data/klines.db"
pool_size = 10
connection_timeout_secs = 30
enable_wal = true

[websocket]
use_proxy = true
proxy_host = "127.0.0.1"
proxy_port = 1080
websocket_url = "wss://fstream.binance.com/ws"
connection_timeout_secs = 30
reconnect_interval_secs = 1
max_reconnect_attempts = 300
heartbeat_interval_secs = 30

[buffer]
initial_capacity = 70000
enable_preallocation = true
alignment_size = 64
# 增量数据缓冲区固定容量 - 用于替换Snapshotter的单缓冲区大小
deltas_buffer_capacity = 5000

[persistence]
batch_size = 1000
queue_size = 50000
write_timeout_secs = 30
enable_compressed_logging = true
# [V8 新增] 高优先级任务的内存缓冲区大小
finalized_buffer_size = 5000
# [V8 新增] 高优先级任务的最大刷盘间隔(毫秒)
finalized_flush_interval_ms = 1000

# ============================================================
# Gateway 配置 - 中心化网关架构
# ============================================================
[gateway]
# Gateway拉取Worker数据的间隔（毫秒）
# 高频模式：为前端WebSocket提供实时数据，每500ms拉取一次
pull_interval_ms = 500

# 单个Worker请求的超时时间（毫秒）
# 应该远小于pull_interval_ms以确保及时响应
pull_timeout_ms = 200

# Worker连续超时的告警阈值
# 超过此次数将触发错误日志
timeout_alert_threshold = 5

[logging]
# 日志系统总开关
enabled = true
log_level = "trace"
log_transport = "named_pipe"
pipe_name = "kline_mcp_log_pipe"
# 是否启用完全追踪功能（包括跨线程上下文传递）
enable_full_tracing = true

# Log MCP Server配置 - 为AI模型提供日志查询服务
[log_mcp_server]
# 命名管道名称（用于接收日志数据）

weblog_pipe_name = "weblog_pipe"
# MCP查询HTTP端口
mcp_port = 9001

# ============================================================
# 构建配置 (仅供PowerShell脚本使用)
# ============================================================
[build]
# 编译模式: "debug" 或 "release"
mode = "debug"

# 审计功能开关: true 启用审计功能，false 禁用审计功能
# 启用时会添加 --features full-audit 参数
# 包含生命周期事件校验和数据完整性审计
enable_audit = true
