# 币安K线系统统一配置文件
# 包含所有服务的配置信息

# ============================================================================
# 编译配置
# ============================================================================
[build]
# 编译模式: "debug" 或 "release"
# debug: 包含调试信息，编译快，体积大，性能较低
# release: 优化编译，编译慢，体积小，性能高
mode = "debug"

# ============================================================================
# 日志配置
# ============================================================================
[logging]
# 全局默认日志级别 (trace, debug, info, warn, error)
default_log_level = "trace"

# 日志传输方式 (named_pipe, file, console)
log_transport = "named_pipe"

# 命名管道名称
pipe_name = "kline_log_pipe"

# ============================================================================
# 服务日志配置
# ============================================================================
[logging.services]
# WebLog服务日志级别（其他服务使用default_log_level）
weblog = "trace"

# ============================================================================
# K线聚合系统配置
# ============================================================================

# 支持的时间周期列表
supported_intervals = ["1m", "5m", "30m", "1h", "4h", "1d", "1w"]

# 最大支持的品种数量
max_symbols = 10000

# 缓冲区切换间隔（毫秒）
buffer_swap_interval_ms = 1000

# 持久化间隔（毫秒）
persistence_interval_ms = 5000

# ============================================================================
# 数据库配置
# ============================================================================
[database]
# 数据库文件路径
database_path = "data/klines.db"

# 连接池大小
pool_size = 10

# 连接超时（秒）
connection_timeout_secs = 30

# 是否启用WAL模式
enable_wal = true

# ============================================================================
# WebSocket配置
# ============================================================================
[websocket]
# 是否使用代理
use_proxy = true

# 代理地址
proxy_host = "127.0.0.1"

# 代理端口
proxy_port = 1080

# WebSocket URL
websocket_url = "wss://fstream.binance.com/ws"

# 连接超时（秒）
connection_timeout_secs = 30

# 重连间隔（秒）
reconnect_interval_secs = 1

# 最大重连次数（5分钟 × 60秒 ÷ 1秒 = 300次）
max_reconnect_attempts = 300

# 心跳间隔（秒）
heartbeat_interval_secs = 30

# ============================================================================
# 缓冲区配置
# ============================================================================
[buffer]
# 初始缓冲区大小
initial_capacity = 70000

# 是否启用预分配
enable_preallocation = true

# 对齐大小
alignment_size = 64

# ============================================================================
# 持久化配置
# ============================================================================
[persistence]
# 批量写入大小
batch_size = 1000

# 写入队列大小
queue_size = 5000

# 写入超时（秒）
write_timeout_secs = 30

# 是否启用压缩日志
enable_compressed_logging = true

# ============================================================================
# WebLog服务配置
# ============================================================================
[weblog]
# Web服务端口
web_port = 8080

# 最大日志条目数
max_log_entries = 10000

# 最大历史日志数
max_history_logs = 1000

# 最大实时日志数
max_realtime_logs = 100
