[package]
name = "kline-macros"
version = "0.1.0"
edition = "2021"
description = "Performance profiling macros for kline server"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
